spring.application.name=auth-service
server.port=8081

# ---- JWT ----
app.jwt.secret=change-me-please-change-me-please-change-me-please
app.jwt.expiration-seconds=3600

# ---- Kafka ----
spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer
app.kafka.enabled=false
app.kafka.topics.user-created=user.created

# ---- Bootstrap admin user ----
app.bootstrap.admin.enabled=true
app.bootstrap.admin.email=admin@talentconnect.tn
app.bootstrap.admin.password=Admin@12345
