sonar.projectKey=TalentConnect-App
sonar.organization=amiraanefzi
sonar.host.url=https://sonarcloud.io

# ── Coverage JaCoCo (tous les services) ──────────────────────────────
sonar.coverage.jacoco.xmlReportPaths=\
  auth-service/target/site/jacoco/jacoco.xml,\
  candidatures-service/target/site/jacoco/jacoco.xml,\
  chatbot-service/target/site/jacoco/jacoco.xml,\
  job-service/target/site/jacoco/jacoco.xml

# ── Classes compilées ─────────────────────────────────────────────────
sonar.java.binaries=\
  auth-service/target/classes,\
  candidatures-service/target/classes,\
  chatbot-service/target/classes,\
  job-service/target/classes

# ── Sources ───────────────────────────────────────────────────────────
sonar.sources=\
  auth-service/src/main/java,\
  candidatures-service/src/main/java,\
  chatbot-service/src/main/java,\
  job-service/src/main/java

# ── Tests ─────────────────────────────────────────────────────────────
sonar.tests=\
  auth-service/src/test/java,\
  candidatures-service/src/test/java,\
  chatbot-service/src/test/java,\
  job-service/src/test/java

# ── Exclusions ────────────────────────────────────────────────────────
sonar.exclusions=**/dto/**,**/model/**,**/entity/**
