sonar.projectKey=TalentConnect-App
sonar.organization=amiraanefzi
sonar.host.url=https://sonarcloud.io
# Token provided via SONAR_LOGIN environment variable or CLI: sonar-scanner -Dsonar.login=TOKEN

# Coverage
sonar.coverage.jacoco.xmlReportPaths=auth-service/target/site/jacoco/jacoco.xml,job-service/target/site/jacoco/jacoco.xml

# Binaries
sonar.java.binaries=auth-service/target/classes,job-service/target/classes

# Sources
sonar.sources=auth-service/src/main/java,job-service/src/main/java

# Tests
sonar.tests=auth-service/src/test/java,job-service/src/test/java

# Excludes
sonar.exclusions=**/dto/**,**/model/**,**/entity/**
