CREATE TABLE candidatures (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    offer_id BIGINT NOT NULL,
    applicant_user_id BIGINT NOT NULL,
    type VARCHAR(30) NOT NULL,
    status VARCHAR(30) NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    cv_file_id VARCHAR(80),
    referral_id BIGINT,
    CONSTRAINT uk_candidature_applicant_offer UNIQUE (applicant_user_id, offer_id)
);

CREATE TABLE candidature_status_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    candidature_id BIGINT NOT NULL,
    from_status VARCHAR(30) NOT NULL,
    to_status VARCHAR(30) NOT NULL,
    changed_at TIMESTAMP NOT NULL,
    changed_by BIGINT NOT NULL,
    changed_by_role VARCHAR(50) NOT NULL,
    CONSTRAINT fk_status_history_candidature
        FOREIGN KEY (candidature_id) REFERENCES candidatures (id)
);

CREATE INDEX idx_candidatures_applicant_user_id ON candidatures (applicant_user_id);
CREATE INDEX idx_candidatures_offer_id ON candidatures (offer_id);
CREATE INDEX idx_candidatures_status ON candidatures (status);
CREATE INDEX idx_status_history_candidature_id ON candidature_status_history (candidature_id);
