sonar.projectKey=TalentConnect-App
sonar.organization=amiraanefzi
sonar.sources=talentconnect-backend/src/main/java
sonar.tests=talentconnect-backend/src/test/java
sonar.java.binaries=talentconnect-backend/target/classes
